"""
Data pipeline: data.gov.il (CBS "Road accidents with casualties - 2024") -> accidents_clean.json / accidents_data.js

All code -> label mappings below were taken from the official CBS "Dictionary - 2024" file
(resource c557fe0c-5f18-41ff-b756-44d26ed4aee4 on the same dataset page).
"""
import urllib.request
import json
import pandas as pd
import numpy as np
from pyproj import Transformer

RESOURCE_ID = '05d14adb-fe54-49f7-b7ce-f30348e2d959'
# There are ~8,300 records, so a limit of 10,000 returns everything in one call
URL = f'https://data.gov.il/api/3/action/datastore_search?resource_id={RESOURCE_ID}&limit=10000'

# --- CBS Dictionary 2024 ---
# Table 4 - accident severity (HUMRAT_TEUNA)
SEVERITY_MAP = {1: 'Fatal', 2: 'Severe', 3: 'Light'}

# Table 39 - day of week (YOM_BASHAVUA)
DAY_MAP = {1: 'Sunday', 2: 'Monday', 3: 'Tuesday', 4: 'Wednesday',
           5: 'Thursday', 6: 'Friday', 7: 'Saturday'}

# Table 5 - accident type (SUG_TEUNA). Code 16 does not exist in the dictionary.
TYPE_MAP = {
    1: 'Pedestrian hit',
    2: 'Front-to-side',
    3: 'Front-to-rear',
    4: 'Side-to-side',
    5: 'Head-on',
    6: 'Hit stopped vehicle',
    7: 'Hit parked vehicle',
    8: 'Hit fixed object',
    9: 'Ran off road / onto sidewalk',
    10: 'Rollover',
    11: 'Skid',
    12: 'Passenger injured inside vehicle',
    13: 'Fall from moving vehicle',
    14: 'Fire',
    15: 'Other',
    17: 'Rear-to-front',
    18: 'Rear-to-side',
    19: 'Animal collision',
    20: 'Hit by vehicle cargo',
}

# Table 2 - road type (SUG_DEREH)
ROAD_MAP = {1: 'Urban - junction', 2: 'Urban - not junction',
            3: 'Intercity - junction', 4: 'Intercity - not junction', 5: 'Off-road'}

# Table 38 - day / night (YOM_LAYLA)
LIGHT_MAP = {1: 'Day', 5: 'Night'}


def main():
    print("Fetching ALL 2024 records from data.gov.il API...")
    with urllib.request.urlopen(URL) as req:
        res = json.loads(req.read())
    if not res.get('success'):
        raise RuntimeError('API returned failure')

    records = res['result']['records']
    print(f"Downloaded {len(records)} records")
    df = pd.DataFrame(records)

    # 1. De-duplication. The API adds a running '_id' to every row, so it must be
    #    dropped first; duplicates are then detected by the CBS accident key.
    df = df.drop(columns=['_id'], errors='ignore')
    before = len(df)
    df = df.drop_duplicates(subset=['pk_teuna_fikt'])
    print(f"Duplicates removed: {before - len(df)}")

    # 2. Numeric codes
    code_cols = ['HUMRAT_TEUNA', 'YOM_BASHAVUA', 'SUG_TEUNA', 'HODESH_TEUNA',
                 'SHAA', 'SUG_DEREH', 'YOM_LAYLA', 'X', 'Y']
    for c in code_cols:
        df[c] = pd.to_numeric(df[c], errors='coerce')

    # 3. Decode categories (dictionary tables above)
    df['severity_label'] = df['HUMRAT_TEUNA'].map(SEVERITY_MAP)
    df['day_name'] = df['YOM_BASHAVUA'].map(DAY_MAP)
    df['accident_type'] = df['SUG_TEUNA'].map(TYPE_MAP).fillna('Other')
    df['road_type'] = df['SUG_DEREH'].map(ROAD_MAP)
    df['light'] = df['YOM_LAYLA'].map(LIGHT_MAP)

    # 4. Time of day. SHAA (table 93) has 96 codes of 15 minutes: 1 = 00:00-00:14 ... 96 = 23:45-23:59
    df['hour'] = np.where(df['SHAA'].between(1, 96), (df['SHAA'] - 1) // 4, np.nan)

    # 5. Invalid locations: 0 / 99 placeholders and unparsable values -> drop
    df['X'] = df['X'].replace([0, 99], np.nan)
    df['Y'] = df['Y'].replace([0, 99], np.nan)
    before = len(df)
    df = df.dropna(subset=['X', 'Y'])
    print(f"Rows without a valid location removed: {before - len(df)}")

    # 6. ITM (EPSG:2039) -> WGS84 (EPSG:4326) for web maps
    transformer = Transformer.from_crs("EPSG:2039", "EPSG:4326", always_xy=True)
    lon, lat = transformer.transform(df['X'].values, df['Y'].values)
    df['lon'] = np.round(lon, 5)   # ~1 m precision is more than enough and keeps the file small
    df['lat'] = np.round(lat, 5)

    # 7. Keep only what the dashboard needs
    out = df[['lat', 'lon', 'severity_label', 'day_name', 'accident_type',
              'HODESH_TEUNA', 'SHAA', 'hour', 'road_type', 'light']].copy()
    out['HODESH_TEUNA'] = out['HODESH_TEUNA'].astype('Int64')
    out['SHAA'] = out['SHAA'].astype('Int64')
    out['hour'] = out['hour'].astype('Int64')
    out = out.astype(object).where(out.notna(), None)

    final_records = out.to_dict(orient='records')
    os.makedirs('data', exist_ok=True)
    with open(os.path.join('data', 'accidents_clean.json'), 'w', encoding='utf-8') as f:
        json.dump(final_records, f, ensure_ascii=False, separators=(',', ':'))

    # Same data as a script, so index.html also works when opened directly from disk
    with open(os.path.join('data', 'accidents_data.js'), 'w', encoding='utf-8') as f:
        f.write('// Generated by build_data.py - lets index.html work when opened directly from disk\n')
        f.write('window.ACCIDENTS = ' + json.dumps(final_records, ensure_ascii=False, separators=(',', ':')) + ';\n')

    print(f"Saved {len(final_records)} clean records to data/accidents_clean.json and data/accidents_data.js")


if __name__ == '__main__':
    main()
